export const productArray = [
  {
    name: "Soft-Shell Jakcet",
    description: "Made using fully waterproof Gore tex Shield® outer fabric",
    image: "./assets/images/ashwini-chaudhary-6_sxKpKd8bI-unsplash.webp",
    id: "1",
    price: 275,
  },
  {
    name: "Exploring Jacket",
    description: "A warm jacket, made using fully waterproof Gore tex Shield® outer fabric",
    image: "./assets/images/becca-tapert-BsiyAubKJGY-unsplash.webp",
    id: "2",
    price: 299,
  },
  {
    name: "Hicking Jakcet",
    description: "A warm jacket that protects you from the winds, made using fully waterproof Gore tex Shield® outer fabric",
    image: "./assets/images/claude-piche-lO9LgCjqsBs-unsplash.webp",
    id: "3",
    price: 199,
  },
  {
    name: "Outdoors Jacket",
    description: "Made using fully waterproof Gore tex Shield® outer fabric",
    image: "./assets/images/jesse-van-vliet--xSXQYY_eHI-unsplash.webp",
    id: "4",
    price: 250,
  },
  {
    name: "Skiing Jacket",
    description: "Made using fully waterproof Gore tex Shield® outer fabric",
    image: "./assets/images/nitish-meena-qs7JjH1yLJ0-unsplash.webp",
    id: "5",
    price: 350,
  },
  {
    name: "Rain Jacket",
    description: "Made using fully waterproof Gore tex Shield® outer fabric",
    image: "./assets/images/pexels-andy-vu-3217911.webp",
    id: "6",
    price: 150,
  },
  {
    name: "Wind Jacket",
    description: "Made using fully waterproof Gore tex Shield® outer fabric",
    image: "./assets/images/pexels-ibadah-mimpi-3365796.webp",
    id: "7",
    price: 265,
  },
  {
    name: "Jacket H",
    description: "Made using fully waterproof Gore tex Shield® outer fabric",
    image: "./assets/images/pexels-michael-block-3225529.webp",
    id: "8",
    price: 375,
  },
  {
    name: "Jacket I",
    description: "A nice jacket",
    image: "./assets/images/pexels-oziel-gómez-925263.webp",
    id: "9",
    price: 200,
  },
  {
    name: "Jacket J",
    description: "A nice jacket",
    image: "./assets/images/pexels-simon-migaj-747470.webp",
    id: "10",
    price: 200,
  },
  {
    name: "Jacket K",
    description: "A nice jacket",
    image: "./assets/images/stephen-arnold-8ItNia0nMVA-unsplash.webp",
    id: "11",
    price: 200,
  },
  {
    name: "Jacket L",
    description: "A nice jacket",
    image: "./assets/images/wesley-tingey-moZDs_YSoHQ-unsplash.webp",
    id: "12",
    price: 200,
  },
];
